# Extensao Wokwi for VS Code.
# Compile antes com PlatformIO (env wokwi) e depois rode "Wokwi: Start Simulator".
[wokwi]
version = 1
firmware = '.pio/build/wokwi/firmware.bin'
elf      = '.pio/build/wokwi/firmware.elf'
